# Generated by Django 4.2.1 on 2023-06-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("attendees", models.IntegerField()),
                ("event_date", models.DateTimeField()),
                ("notes", models.TextField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="persons.client"
                    ),
                ),
                (
                    "event_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="events.eventstatus",
                    ),
                ),
                (
                    "support_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persons.employee",
                    ),
                ),
            ],
        ),
    ]
