# Generated by Django 4.2.1 on 2023-07-04 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persons", "0001_initial"),
        ("events", "0001_initial"),
        ("contracts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="persons.client"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="contracts.contract"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="events.eventstatus"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="support_contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
