# Generated by Django 4.2.1 on 2023-06-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0002_client_first_name_client_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.CharField(default="test@test.fr", max_length=250),
            preserve_default=False,
        ),
    ]
