# Generated by Django 4.2.1 on 2023-06-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0003_client_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
