# Generated by Django 4.2.1 on 2023-06-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0004_alter_employee_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="group",
        ),
    ]
